# Generated by Django 5.2.14 on 2026-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_crud', '0002_student_city_student_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.AddField(
            model_name='student',
            name='contact_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
