# Generated by Django 5.2.14 on 2026-05-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_crud', '0004_alter_student_age_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
